version: '3.9'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  mysql:
    image: mysql
    container_name: database
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xdayman1
      MYSQL_DATABASE: longfull
    ports:
      - 3306:3306
    restart: always

  laravel:
    depends_on:
      - mysql
    build: .
    container_name: laravel
    ports:
      - 8000:8000
    restart: always

volumes:
  db-data:
